### ISSUE TITLE
Missing endframe in sendLeds function

### ISSUE THREAD

**Issue by RikWesselink** [SerafinTech/node-apa102-spi#3]
In apa102-spi.js the function sendLeds is not sending the 'endframe' to the ledstrip. It seems the behaviour of the final led, or leds, is inconsistent without it. Adding 1 bits at the end is required. According to the datasheet it should be 32 bits with the value 1. But I've read online that it actually needs to be at least 0.5*nrOfLeds. So 32 will work up to 64 leds.

For me (60 leds) this works (I added only the first two lines in the function):

```
Apa102spi.prototype.sendLeds = function () {
  this.bufferLength += 4;
  this.writeBuffer = Buffer.concat([this.writeBuffer, Buffer.alloc(4, '11111111', 'hex')], this.bufferLength);
  
  rpio.spiWrite(this.writeBuffer, this.bufferLength)
}
```

**Comment by RikWesselink** [comment]
I can reproduce the issue and the proposed solution was not correct. It increases the buffer size again and again. It still seems that the endframe is missing, but it works now.

**Comment by SerafinTech** [comment]
I previously had the end frame on there, but it is not necessary and actually caused some versions of LEDs to have problems. I have previously used this library with a 4 matrices of 256 LEDs without a problem.  Sometimes too low of a frequency divider will cause malfunction of some of the LEDs. Also long wires from Pi or 3.3 to 5v converter can cause issues.

**Comment by RikWesselink** [comment]
It still gave some issues for me (without the endframe). Solved it by adding the endframe in the function Apa102spi, not in the sendLeds function as I mistakenly did before.

function Apa102spi (stringLength, clockDivider) {
  clockDivider = typeof clockDivider !== 'undefined' ? clockDivider : 200
  this.bufferLength = stringLength * 4
  this.writeBuffer = Buffer.alloc(this.bufferLength, 'E0000000', 'hex')
  this.bufferLength += 4
  this.writeBuffer = Buffer.concat([Buffer.alloc(4, '00000000', 'hex'), this.writeBuffer], this.bufferLength)
  
  //--- added by Rik, missing end-byte ---//
  this.bufferLength += 4;
  this.writeBuffer = Buffer.concat([this.writeBuffer, Buffer.alloc(4, '11111111', 'hex')], this.bufferLength);
  //--- end of addition ---//
  
  rpio.spiBegin()
  rpio.spiSetClockDivider(clockDivider)
}
